version: 0.0
os: linux
files:
  - source: /FrontEnd/dist
    destination: //opt/tomcat/webapps/data-validation
  - source: /API/target/API-0.0.1
    destination: //opt/tomcat/webapps/data-validation
hooks:
  ApplicationStop:
    - location: aws_scripts/stop_servers
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_scripts/start_servers
      timeout: 300
      runas: root
